// src/components/TurnaroundMap/index.tsx
import React, {useEffect, useRef, useState} from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

import {I18N, type RegionCode} from '@site/src/components/i18n';
import styles from './styles.module.css';

type Locale = 'en' | 'fr';

type TurnaroundRegion = {
  name?: string;
  code: RegionCode;
  svgIds?: string[];
  enabled: boolean;
};

type TurnaroundData = {
  definition?: string;
  regions: TurnaroundRegion[];
};

function getLocale(currentLocale: string): Locale {
  return currentLocale.toLowerCase().startsWith('fr') ? 'fr' : 'en';
}

function stripSvgXmlDeclaration(svg: string): string {
  return svg.replace(/^\s*<\?xml[^>]*\?>\s*/i, '');
}

function classForEnabled(enabled: boolean): string {
  return enabled ? 'enabled' : 'disabled';
}

function scrollToRegion(code: string): void {
  const target = document.getElementById(`region-${code}`);

  if (!target) return;

  target.scrollIntoView({behavior: 'smooth', block: 'start'});
  target.classList.add('region-flash');

  window.setTimeout(() => {
    target.classList.remove('region-flash');
  }, 900);
}

export default function TurnaroundMap(): React.JSX.Element {
  const {i18n} = useDocusaurusContext();
  const locale = getLocale(i18n.currentLocale);
  const t = I18N[locale] ?? I18N.en;

  const mapUrl = useBaseUrl('/maps/dfo-regions.svg');
  const dataUrl = useBaseUrl(`/data/turnaround.json`);

  const mapRef = useRef<HTMLDivElement | null>(null);

  const [svg, setSvg] = useState('');
  const [data, setData] = useState<TurnaroundData>({
    definition: '',
    regions: [],
  });
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    async function loadMapData() {
      try {
        setError('');

        const [svgResponse, dataResponse] = await Promise.all([
          fetch(mapUrl, {cache: 'no-store'}),
          fetch(dataUrl, {cache: 'no-store'}),
        ]);

        if (!svgResponse.ok) {
          throw new Error(`HTTP ${svgResponse.status} loading ${mapUrl}`);
        }

        if (!dataResponse.ok) {
          throw new Error(`HTTP ${dataResponse.status} loading ${dataUrl}`);
        }

        const rawSvg = await svgResponse.text();

        if (!rawSvg.includes('<svg')) {
          throw new Error('Map file did not contain <svg> markup.');
        }

        const contentType = dataResponse.headers.get('content-type') || '';

        if (!contentType.includes('application/json')) {
          const snippet = (await dataResponse.text()).slice(0, 120);
          throw new Error(
            `Expected JSON but got "${contentType}". Body starts: ${snippet}`,
          );
        }

        const json = (await dataResponse.json()) as TurnaroundData;

        if (cancelled) return;

        setSvg(stripSvgXmlDeclaration(rawSvg));
        setData({
          definition: json.definition ?? '',
          regions: Array.isArray(json.regions) ? json.regions : [],
        });
      } catch (e) {
        if (cancelled) return;

        setError(e instanceof Error ? e.message : String(e));
      }
    }

    loadMapData();

    return () => {
      cancelled = true;
    };
  }, [mapUrl, dataUrl]);

  useEffect(() => {
    if (!svg || data.regions.length === 0 || !mapRef.current) return;

    const root = mapRef.current;
    const cleanupHandlers: Array<() => void> = [];

    for (const region of data.regions) {
      const statusClass = classForEnabled(region.enabled);
      const regionLabel = t.regions[region.code];
      const statusLabel = region.enabled
        ? t.turnaroundEnabled
        : t.turnaroundDisabled;

      for (const id of region.svgIds ?? []) {
        const element = root.querySelector<SVGElement>(`#${CSS.escape(id)}`);

        if (!element) continue;

        element.classList.add('region-fill', statusClass);
        element.setAttribute('data-region', regionLabel);
        element.setAttribute('tabindex', '0');
        element.setAttribute('role', 'button');

        // Prevent duplicate <title> elements if the effect re-runs.
        element.querySelector('title')?.remove();

        const title = document.createElementNS(
          'http://www.w3.org/2000/svg',
          'title',
        );

        title.textContent = `${regionLabel}\n${statusLabel}`;
        element.appendChild(title);

        const handleClick = (event: Event) => {
          event.preventDefault();
          scrollToRegion(region.code);
        };

        const handleKeydown = (event: KeyboardEvent) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            scrollToRegion(region.code);
          }
        };

        element.addEventListener('click', handleClick);
        element.addEventListener('keydown', handleKeydown);

        cleanupHandlers.push(() => {
          element.removeEventListener('click', handleClick);
          element.removeEventListener('keydown', handleKeydown);
        });
      }
    }

    return () => {
      cleanupHandlers.forEach((cleanup) => cleanup());
    };
  }, [svg, data.regions, t]);

  return (
    <div className={styles.mapCard}>
      <h3 className={styles.mapTitle}>{t.turnaroundMapTitle}</h3>

      {data.definition ? (
        <p className={styles.mapSubtitle}>{t.turnaroundDefinition}</p>
      ) : null}

      {error ? (
        <div className={styles.mapError}>Failed to load map/data: {error}</div>
      ) : (
        <div
          ref={mapRef}
          className={styles.mapWrap}
          dangerouslySetInnerHTML={{__html: svg}}
        />
      )}

      <div className={styles.mapLegend}>
        <span className={`${styles.swatch} ${styles.enabled}`} />
        {t.turnaroundEnabled}

        <span className={`${styles.swatch} ${styles.disabled}`} />
        {t.turnaroundDisabled}
      </div>
    </div>
  );
}

// widgets/.vuepress/components/TurnaroundMap.vue
<template>
  <div class="map-card">
    <h3 class="map-title">{{ t.turnaroundMapTitle }}</h3>

    <p v-if="data.definition" class="map-subtitle">{{ data.definition }}</p>

    <div v-if="error" class="map-error">
      Failed to load map/data: {{ error }}
    </div>

    <div v-else class="map-wrap" v-html="svg"></div>

    <div class="map-legend">
      <span class="swatch enabled"></span> {{ t.turnaroundEnabled }}
      <span class="swatch disabled"></span> {{ t.turnaroundDisabled }}
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, nextTick, computed } from "vue";
import { usePageData } from "vuepress/client";
import { I18N } from "./i18n";

const page = usePageData();

const locale = computed(() =>
  (page.value.lang || "").toLowerCase().startsWith("fr") ? "fr" : "en"
);

const t = computed(() => I18N[locale.value] ?? I18N.en);

const svg = ref("");
const error = ref("");

const data = reactive({
  definition: "",
  regions: [],
});

function classForEnabled(enabled) {
  return enabled ? "enabled" : "disabled";
}

function scrollToRegion(code) {
  const el = document.getElementById(`region-${code}`);
  if (!el) return;

  el.scrollIntoView({ behavior: "smooth", block: "start" });
  el.classList.add("region-flash");
  setTimeout(() => el.classList.remove("region-flash"), 900);
}

onMounted(async () => {
  try {
    const [svgRes, dataRes] = await Promise.all([
      fetch("/maps/dfo-regions.svg", { cache: "no-store" }),
      fetch(`/data/turnaround.${locale.value}.json`, { cache: "no-store" }),
    ]);

    if (!svgRes.ok) throw new Error(`HTTP ${svgRes.status} loading /maps/dfo-regions.svg`);
    if (!dataRes.ok) throw new Error(`HTTP ${dataRes.status} loading turnaround data`);

    const rawSvg = await svgRes.text();
    if (!rawSvg.includes("<svg")) {
      throw new Error("Map file did not contain <svg> markup");
    }

    svg.value = rawSvg.replace(/^\s*<\?xml[^>]*\?>\s*/i, "");

    const ct = dataRes.headers.get("content-type") || "";
    if (!ct.includes("application/json")) {
      const snippet = (await dataRes.text()).slice(0, 120);
      throw new Error(`Expected JSON but got "${ct}". Body starts: ${snippet}`);
    }

    const json = await dataRes.json();
    data.definition = json.definition ?? "";
    data.regions = Array.isArray(json.regions) ? json.regions : [];

    await nextTick();

    for (const r of data.regions) {
      const cls = classForEnabled(!!r.enabled);

      for (const id of r.svgIds ?? []) {
        const el = document.getElementById(id);
        if (el) {
          el.classList.add("region-fill", cls);
          el.setAttribute("data-region", r.name);

          

          const title = document.createElementNS(
          "http://www.w3.org/2000/svg",
          "title"
          );

          title.textContent =
          `${r.code} — ${r.name}\n${r.enabled ? t.value.turnaroundEnabled : t.value.turnaroundDisabled}`;

          el.appendChild(title);
          el.style.cursor = "pointer";
          el.addEventListener("click", (evt) => {
            evt.preventDefault();
            scrollToRegion(r.code);
          });
        }
      }
    }
  } catch (e) {
    error.value = String(e?.message || e);
  }
});
</script>

<style scoped>
.map-card {
  border: 1px solid var(--c-border);
  border-radius: 12px;
  padding: 16px;
  background: var(--c-bg);
}

.map-title { margin: 0 0 10px 0; }
.map-subtitle { margin: 0 0 12px 0; color: var(--c-text-quote); }

.map-error {
  padding: 10px 12px;
  border: 1px solid var(--c-map-border);
  border-radius: 10px;
  background: var(--c-bg-soft);
}

.map-wrap {
  min-height: 220px;
}

.map-wrap :deep(svg) {
  width: 100%;
  height: auto;
  max-height: 520px;
}

.map-wrap :deep(.dfo-region) {
  fill: var(--c-bg-soft);
  stroke: var(--c-map-border);
  stroke-width: 0.7;
}

.map-wrap :deep(.region-fill.enabled) {
  fill: color-mix(in srgb, var(--c-brand) 70%, white);
  stroke: var(--c-map-border);
  stroke-width: 0.7;
}

.map-wrap :deep(.region-fill.disabled) {
  fill: var(--c-bg-soft);
  stroke: var(--c-map-border);
  stroke-width: 0.7;
}

.map-wrap :deep(.region-fill:hover) {
  filter: brightness(0.95);
}

.map-legend {
  display: flex;
  gap: 10px;
  align-items: center;
  flex-wrap: wrap;
  margin-top: 12px;
  color: var(--c-text-quote);
}

.swatch {
  width: 14px;
  height: 14px;
  border-radius: 4px;
  border: 1px solid var(--c-border);
  display: inline-block;
  margin: 0 4px 0 12px;
}

.swatch.enabled {
  background: color-mix(in srgb, var(--c-brand) 70%, white);
}

.swatch.disabled {
  background: var(--c-bg-soft);
}
</style>
