// src/components/DfoRegionsMap/index.tsx
import React, {useEffect, useMemo, useRef, useState} from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Heading from '@theme/Heading'

import {I18N, type RegionCode, RoleKey} from '@site/src/components/i18n';
import styles from './styles.module.css';

type Locale = 'en' | 'fr';

type Status = 'complete' | 'scheduled' | 'in_progress' | 'not_started';

type OnboardingGroup = {
  role: RoleKey;
  status?: Status;
  date?: string;
};

type Region = {
  code: RegionCode;
  svgIds?: string[];
  groups?: OnboardingGroup[];
};

type OnboardingData = {
  regions: Region[];
};

const SVG_ID_TO_CODE: Record<string, string> = {
  DFO_NL: 'NL',
  DFO_PAC: 'PAC',
  DFO_ONT_PRA: 'ONT_PRA',
  DFO_QC: 'QC',
  DFO_ARCTIC: 'ARCTIC',
  DFO_MAR: 'MAR',
  DFO_GULF: 'GULF',
  DFO_NCR: 'NCR',
};

function getLocale(currentLocale: string): Locale {
  return currentLocale.toLowerCase().startsWith('fr') ? 'fr' : 'en';
}

function completionScore(region: Region): number {
  const groups = region.groups ?? [];
  return groups.filter((group) => group.status === 'complete').length;
}

function classForScore(score: number): string {
  if (score >= 3) return styles.score3;
  if (score === 2) return styles.score2;
  if (score === 1) return styles.score1;
  return styles.score0;
}

function plainScoreClass(score: number): string {
  if (score >= 3) return 'score-3';
  if (score === 2) return 'score-2';
  if (score === 1) return 'score-1';
  return 'score-0';
}

function stripSvgXmlDeclaration(svg: string): string {
  return svg.replace(/^\s*<\?xml[^>]*\?>\s*/i, '');
}

function scrollToRegion(code: string): void {
  const target = document.getElementById(`region-${code}`);

  if (!target) return;

  target.scrollIntoView({behavior: 'smooth', block: 'start'});
  target.classList.add('region-flash');

  window.setTimeout(() => {
    target.classList.remove('region-flash');
  }, 900);
}

export default function DfoRegionsMap(): React.JSX.Element {
  const {i18n} = useDocusaurusContext();
  const locale = getLocale(i18n.currentLocale);
  const t = I18N[locale] ?? I18N.en;

  const mapUrl = useBaseUrl('/maps/dfo-regions.svg');
  const dataUrl = useBaseUrl(`/data/onboarding.json`);

  const mapRef = useRef<HTMLDivElement | null>(null);

  const [svg, setSvg] = useState('');
  const [regions, setRegions] = useState<Region[]>([]);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    async function loadMapData() {
      try {
        setError('');

        const [svgResponse, dataResponse] = await Promise.all([
          fetch(mapUrl, {cache: 'no-store'}),
          fetch(dataUrl, {cache: 'no-store'}),
        ]);

        if (!svgResponse.ok) {
          throw new Error(`HTTP ${svgResponse.status} loading ${mapUrl}`);
        }

        if (!dataResponse.ok) {
          throw new Error(`HTTP ${dataResponse.status} loading ${dataUrl}`);
        }

        const rawSvg = await svgResponse.text();

        if (!rawSvg.includes('<svg')) {
          throw new Error('Map file did not contain <svg> markup.');
        }

        const json = (await dataResponse.json()) as OnboardingData;

        if (cancelled) return;

        setSvg(stripSvgXmlDeclaration(rawSvg));
        setRegions(Array.isArray(json.regions) ? json.regions : []);
      } catch (e) {
        if (cancelled) return;

        setError(e instanceof Error ? e.message : String(e));
      }
    }

    loadMapData();

    return () => {
      cancelled = true;
    };
  }, [mapUrl, dataUrl]);

  useEffect(() => {
    if (!svg || regions.length === 0 || !mapRef.current) return;

    const root = mapRef.current;

    for (const region of regions) {
      const score = completionScore(region);
      const scoreClass = plainScoreClass(score);

      for (const id of region.svgIds ?? []) {
        const element = root.querySelector<SVGElement>(`#${CSS.escape(id)}`);

        if (!element) continue;

        element.classList.add('region-fill', scoreClass);
        element.setAttribute('data-region', `${t.regions[region.code]}`);
        element.setAttribute('tabindex', '0');
        element.setAttribute('role', 'button');

        const title = document.createElementNS(
          'http://www.w3.org/2000/svg',
          'title',
        );

        title.textContent = `${t.regions[region.code]}\n${score}/3 ${t.complete}`;
        element.appendChild(title);
      }
    }

    const cleanupHandlers: Array<() => void> = [];

    for (const [svgId, code] of Object.entries(SVG_ID_TO_CODE)) {
      const element = root.querySelector<SVGElement>(`#${CSS.escape(svgId)}`);

      if (!element) continue;

      const handleClick = (event: Event) => {
        event.preventDefault();
        scrollToRegion(code);
      };

      const handleKeydown = (event: KeyboardEvent) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          scrollToRegion(code);
        }
      };

      element.addEventListener('click', handleClick);
      element.addEventListener('keydown', handleKeydown);

      cleanupHandlers.push(() => {
        element.removeEventListener('click', handleClick);
        element.removeEventListener('keydown', handleKeydown);
      });
    }

    return () => {
      cleanupHandlers.forEach((cleanup) => cleanup());
    };
  }, [svg, regions, t.complete]);

  const legendItems = useMemo(
    () => [
      {label: '0/3', className: styles.swatch0},
      {label: '1/3', className: styles.swatch1},
      {label: '2/3', className: styles.swatch2},
      {label: '3/3', className: styles.swatch3},
    ],
    [],
  );

  return (
    <div className={styles.mapCard}>
      <Heading as='h3' className={styles.mapTitle}>{t.mapTitle}</Heading>

      {error ? (
        <div className={styles.mapError}>Failed to load map/data: {error}</div>
      ) : (
        <div
          ref={mapRef}
          className={styles.mapWrap}
          dangerouslySetInnerHTML={{__html: svg}}
        />
      )}

      <div className={styles.mapLegend}>
        {legendItems.map((item) => (
          <React.Fragment key={item.label}>
            <span className={`${styles.swatch} ${item.className}`} />
            {item.label}
          </React.Fragment>
        ))}
      </div>
    </div>
  );
}

// docs/.vuepress/components/DfoRegionsMap.vue
<template>
  <div class="map-card">
    <h3 class="map-title">{{ t.mapTitle }}</h3>

    <div v-if="error" class="map-error">Failed to load map/data: {{ error }}</div>

    <div v-else class="map-wrap" v-html="svg"></div>

    <div class="map-legend">
      <span class="swatch s0"></span> 0/3
      <span class="swatch s1"></span> 1/3
      <span class="swatch s2"></span> 2/3
      <span class="swatch s3"></span> 3/3
    </div>
  </div>
</template>

<script setup>
import { computed, ref, onMounted, nextTick } from "vue";
import { usePageData } from "vuepress/client";
import { I18N } from "./i18n";
import { useRoute } from "vue-router";

const page = usePageData();
const route = useRoute();
const locale = computed(() =>
  (page.value.lang || "").toLowerCase().startsWith("fr") ? "fr" : "en");
const t = computed(() => I18N[locale.value] ?? I18N.en);


const base = computed(() => site.value.base);

const svg = ref("");
const error = ref("");

const SVG_ID_TO_CODE = {
  DFO_NL: "NL",
  DFO_PAC: "PAC",
  DFO_ONT_PRA: "ONT_PRA",
  DFO_QC: "QC",
  DFO_ARCTIC: "ARCTIC",
  DFO_MAR: "MAR",
  DFO_GULF: "GULF",
  DFO_NCR: "NCR",
};

function completionScore(region) {
  const groups = region.groups ?? [];
  return groups.filter((g) => g.status === "complete").length; // 0..3
}

function classForScore(score) {
  return score === 3 ? "s3" : score === 2 ? "s2" : score === 1 ? "s1" : "s0";
}

onMounted(async () => {
  try {
    const url = `/data/onboarding.${locale.value}.json`;
    const [svgRes, dataRes] = await Promise.all([
      fetch("/maps/dfo-regions.svg", { cache: "no-store" }),
      fetch(url, { cache: "no-store" }),
    ]);

    if (!svgRes.ok) throw new Error(`HTTP ${svgRes.status} loading /maps/dfo-regions.svg`);
    if (!dataRes.ok) throw new Error(`HTTP ${dataRes.status} loading /data/onboarding.json`);

    const rawSvg = await svgRes.text();
    if (!rawSvg.includes("<svg")) {
       throw new Error("Map file did not contain <svg> markup (check path /maps/dfo-regions.svg)");
       }
      // Strip XML declaration (breaks when injecting via v-html in HTML parser)
   svg.value = rawSvg.replace(/^\s*<\?xml[^>]*\?>\s*/i, "");
    const data = await dataRes.json();

    await nextTick(); // ensure v-html has inserted the SVG

    const regions = data.regions ?? [];

    // Color each province/territory by its region score
    for (const r of regions) {
      const score = completionScore(r);
      const cls = classForScore(score);

      for (const id of r.svgIds ?? []) {
        const el = document.getElementById(id);
        if (el) {
          el.classList.add("region-fill", cls);
          el.setAttribute("data-region", r.name);
          
          const title = document.createElementNS(
          "http://www.w3.org/2000/svg",
          "title"
          );
          title.textContent = `${r.name}\n${score}/3 complete`;
          el.appendChild(title);
        }
      }
    }
    function scrollToRegion(code) {
      const id = `region-${code}`;
      const el = document.getElementById(id);

      if (!el) return;

      el.scrollIntoView({ behavior: "smooth", block: "start" });

      // Optional: a quick highlight pulse
      el.classList.add("region-flash");
      setTimeout(() => el.classList.remove("region-flash"), 900);
    }

    // Make SVG regions clickable
    for (const [svgId, code] of Object.entries(SVG_ID_TO_CODE)) {
      const el = document.getElementById(svgId);
      if (!el) continue;

      el.style.cursor = "pointer";
      el.addEventListener("click", (evt) => {
        evt.preventDefault();
        scrollToRegion(code);
      });

  // Keyboard accessibility (nice touch)
  el.setAttribute("tabindex", "0");
  el.setAttribute("role", "button");
  el.addEventListener("keydown", (evt) => {
    if (evt.key === "Enter" || evt.key === " ") {
      evt.preventDefault();
      scrollToRegion(code);
    }
  });
}
  }
  catch (e) {
    error.value = String(e?.message || e);
  }
});
</script>

<style scoped>
.map-card {
  border: 1px solid var(--c-border);
  border-radius: 12px;
  padding: 16px;
  background: var(--c-bg);
}
.map-title { margin: 0 0 10px 0; }
.map-error {
  padding: 10px 12px;
  border: 1px solid var(--c-map-border);
  border-radius: 10px;
  background: var(--c-bg-soft);
}

.map-wrap :deep(svg) {
  width: 100%;
  height: auto;
  max-height: 520px;
}

.map-wrap :deep(.region-fill) {
  stroke: var(--c-map-border);
  stroke-width: 0.7;
}

.map-wrap :deep(.dfo-region) {
  fill: var(--c-bg-soft);
  stroke: var(--c-map-border);
  stroke-width: 0.7;
}

/* Use your theme colors; these are intentionally subtle */
.map-wrap :deep(.region-fill.s0) { fill: var(--c-bg-soft); }
.map-wrap :deep(.region-fill.s1) { fill: color-mix(in srgb, var(--c-brand) 50%, white); }
.map-wrap :deep(.region-fill.s2) { fill: color-mix(in srgb, var(--c-brand) 75%, white); }
.map-wrap :deep(.region-fill.s3) { fill: color-mix(in srgb, var(--c-brand) 100%, white); }

/* Hover hint */
.map-wrap :deep(.region-fill:hover) {
  filter: brightness(0.50);
  cursor: pointer;
}

.map-legend {
  display: flex;
  gap: 10px;
  align-items: center;
  flex-wrap: wrap;
  margin-top: 12px;
  color: var(--c-text-quote);
  font-variant-numeric: tabular-nums;
}
.swatch {
  width: 14px;
  height: 14px;
  border-radius: 4px;
  border: 1px solid var(--c-border);
  display: inline-block;
  margin: 0 4px 0 12px;
}
.swatch.s0 { background: var(--c-bg-soft); }
.swatch.s1 { background: color-mix(in srgb, var(--c-brand) 20%, white); }
.swatch.s2 { background: color-mix(in srgb, var(--c-brand) 45%, white); }
.swatch.s3 { background: color-mix(in srgb, var(--c-brand) 75%, white); }
</style>
