// src/components/OnboardingWidget/index.tsx
import React, {useEffect, useMemo, useState} from 'react';
import clsx from 'clsx';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

import {I18N, formatDate, type RegionCode, RoleKey} from '@site/src/components/i18n';
import styles from './styles.module.css';

type Locale = 'en' | 'fr';

type Status = 'complete' | 'scheduled' | 'in_progress' | 'not_started';

type OnboardingGroup = {
  role: RoleKey;
  status?: Status;
  date?: string;
};

type Region = {
  name: string;
  code: RegionCode;
  groups?: OnboardingGroup[];
};

type OnboardingData = {
  definition?: string;
  regions: Region[];
};

type FlatGroup = {
  region: string;
  regionCode: string;
  group: string;
  status: Status;
  date?: string;
  key: string;
};

function getLocale(currentLocale: string): Locale {
  return currentLocale.toLowerCase().startsWith('fr') ? 'fr' : 'en';
}

function getStatusLabel(status: Status | undefined, locale: Locale): string {
  const t = I18N[locale] ?? I18N.en;

  switch (status) {
    case 'complete':
      return t.complete;
    case 'scheduled':
      return t.scheduled;
    case 'in_progress':
      return t.inProgress;
    case 'not_started':
    default:
      return t.notStarted;
  }
}

function regionComplete(region: Region): number {
  return (region.groups ?? []).filter((group) => group.status === 'complete').length;
}

export default function OnboardingWidget(): React.JSX.Element {
  const {i18n} = useDocusaurusContext();
  const locale = getLocale(i18n.currentLocale);
  const t = I18N[locale] ?? I18N.en;

  const dataUrl = useBaseUrl(`/data/onboarding.json`);

  const [data, setData] = useState<OnboardingData>({
    definition: '',
    regions: [],
  });

  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    async function loadOnboardingData() {
      try {
        setError('');

        const response = await fetch(dataUrl, {cache: 'no-store'});

        if (!response.ok) {
          throw new Error(`HTTP ${response.status} loading ${dataUrl}`);
        }

        const json = await response.json();

        if (cancelled) return;

        setData({
          definition: json.definition ?? '',
          regions: Array.isArray(json.regions) ? json.regions : [],
        });
      } catch (e) {
        if (cancelled) return;

        setError(e instanceof Error ? e.message : String(e));
      }
    }

    loadOnboardingData();

    return () => {
      cancelled = true;
    };
  }, [dataUrl]);

  const regions = data.regions ?? [];

  const allGroups = useMemo<FlatGroup[]>(
    () =>
      regions.flatMap((region) =>
        (region.groups ?? []).map((group) => ({
          region: t.regions[region.code],
          regionCode: region.code,
          group: t.roles[group.role],
          status: group.status ?? 'not_started',
          date: group.date,
          key: `${region.code}:${group.role}`,
        })),
      ),
    [regions],
  );

  const totalCount = allGroups.length;

  const completedCount = useMemo(
    () => allGroups.filter((group) => group.status === 'complete').length,
    [allGroups],
  );

  const percentComplete = totalCount ? (completedCount / totalCount) * 100 : 0;

  const upcoming = useMemo(
    () =>
      allGroups
        .filter((group) => group.status === 'scheduled' && group.date)
        .sort((a, b) => String(a.date).localeCompare(String(b.date))),
    [allGroups],
  );

  return (
    <div className={styles.onboardCard}>
      {error ? (
        <div className={styles.onboardError}>
          Failed to load onboarding data: {error}
        </div>
      ) : (
        <>
          <div className={styles.onboardSummary}>
            <div>
              <strong>{completedCount}</strong> / {totalCount} {t.sessionsComplete}
            </div>

            <div className={styles.onboardBar}>
              <div
                className={styles.onboardBarFill}
                style={{width: `${percentComplete}%`}}
              />
            </div>

            <div className={styles.onboardPercent}>
              {percentComplete.toFixed(0)}%
            </div>
          </div>

          <div className={styles.onboardGrid}>
            {regions.map((region) => (
              <div
                key={region.code}
                className={styles.onboardRegion}
                id={`region-${region.code}`}
              >
                <div className={styles.onboardRegionHeader}>
                  <div className={styles.onboardRegionName}>{t.regions[region.code]}</div>

                  <div className={styles.onboardRegionCount}>
                    {regionComplete(region)}/{region.groups?.length ?? 0}
                  </div>
                </div>

                <ul className={styles.onboardGroups}>
                  {(region.groups ?? []).map((group) => {
                    const status = group.status ?? 'not_started';

                    return (
                      <li key={t.roles[group.role]} className={styles.onboardGroup}>
                        <span
                          className={clsx(
                            styles.badge,
                            styles[`badge_${status}`],
                          )}
                        >
                          {getStatusLabel(status, locale)}
                        </span>

                        <span className={styles.groupName}>{t.roles[group.role]}</span>

                        {group.date ? (
                          <span className={styles.groupDate}>
                            {formatDate(group.date, locale)}
                          </span>
                        ) : null}
                      </li>
                    );
                  })}
                </ul>
              </div>
            ))}
          </div>

          {upcoming.length > 0 ? (
            <div className={styles.onboardUpcoming}>
              <h3 className={styles.onboardUpcomingTitle}>{t.upcomingTitle}</h3>

              <ul>
                {upcoming.map((item) => (
                  <li key={item.key}>
                    <strong>
                      {item.date ? formatDate(item.date, locale) : '—'}
                    </strong>{' '}
                    — {item.region} ({item.group})
                  </li>
                ))}
              </ul>
            </div>
          ) : null}
        </>
      )}
    </div>
  );
}

// docs/.vuepress/components/OnboardingWidget.vue
<template>
  <div class="onboard-card">
    <!-- Optional titles (keep commented if you want) -->
    <!--
    <h2 class="onboard-title">{{ t.onboardingTitle }}</h2>
    <p v-if="data.definition" class="onboard-subtitle">{{ data.definition }}</p>
    -->

    <div v-if="error" class="onboard-error">
      Failed to load onboarding data: {{ error }}
    </div>

    <template v-else>
      <div class="onboard-summary">
        <div>
          <strong>{{ completedCount }}</strong> / {{ totalCount }} {{ t.sessionsComplete }}
        </div>

        <div class="onboard-bar">
          <div class="onboard-bar-fill" :style="{ width: percentComplete + '%' }"></div>
        </div>

        <div class="onboard-percent">{{ percentComplete.toFixed(0) }}%</div>
      </div>

      <div class="onboard-grid">
        <div
          v-for="r in regions"
          :key="r.code"
          class="onboard-region"
          :id="`region-${r.code}`"
        >
          <div class="onboard-region-header">
            <div class="onboard-region-name">{{ r.name }}</div>
            <div class="onboard-region-count">
              {{ regionComplete(r) }}/{{ (r.groups?.length ?? 0) }}
            </div>
          </div>

          <ul class="onboard-groups">
            <li v-for="g in (r.groups ?? [])" :key="g.name" class="onboard-group">
              <span class="badge" :class="'badge-' + (g.status || 'not_started')">
                {{ label(g.status) }}
              </span>

              <span class="group-name">{{ g.name }}</span>

              <span v-if="g.date" class="group-date">
                {{ formatDate(g.date, locale) }}
              </span>
            </li>
          </ul>
        </div>
      </div>

      <div v-if="upcoming.length" class="onboard-upcoming">
        <h3 class="onboard-upcoming-title">{{ t.upcomingTitle }}</h3>
        <ul>
          <li v-for="u in upcoming" :key="u.key">
            <strong v-if="u.date">{{ formatDate(u.date, locale) }}</strong>
            <strong v-else>—</strong>
            — {{ u.region }} ({{ u.group }})
          </li>
        </ul>
      </div>
    </template>
  </div>
</template>

<script setup>
import { reactive, ref, computed, onMounted } from "vue";
import { useSiteData } from "vuepress/client";
import { I18N, formatDate } from "./i18n";
import { useRoute } from "vue-router";

const route = useRoute();
const locale = route.path.startsWith("/fr/") ? "fr" : "en";
const t = I18N[locale];

const site = useSiteData();
const base = computed(() => site.value.base);
const error = ref("");

const data = reactive({
  definition: "",
  regions: [], // important: always an array
});

onMounted(async () => {
  try {
    const url = `/data/onboarding.${locale}.json`;
    const res = await fetch(url, { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status} loading /data/onboarding.${locale}.json`);
    const json = await res.json();

    data.definition = json.definition ?? "";
    data.regions = Array.isArray(json.regions) ? json.regions : [];
  } catch (e) {
    error.value = String(e?.message || e);
  }
});

const regions = computed(() => data.regions ?? []);

const allGroups = computed(() =>
  regions.value.flatMap((r) =>
    (r.groups ?? []).map((g) => ({
      region: r.name,
      regionCode: r.code,
      group: g.name,
      status: g.status ?? "not_started",
      date: g.date,
      key: `${r.code}:${g.name}`,
    }))
  )
);

const totalCount = computed(() => allGroups.value.length);

const completedCount = computed(
  () => allGroups.value.filter((g) => g.status === "complete").length
);

const percentComplete = computed(() =>
  totalCount.value ? (completedCount.value / totalCount.value) * 100 : 0
);

const upcoming = computed(() =>
  allGroups.value
    .filter((g) => g.status === "scheduled" && g.date)
    .sort((a, b) => String(a.date).localeCompare(String(b.date)))
);

function regionComplete(region) {
  return (region.groups ?? []).filter((g) => (g.status ?? "") === "complete").length;
}

function label(status) {
  switch (status) {
    case "complete":
      return "Complete";
    case "scheduled":
      return "Scheduled";
    case "in_progress":
      return "In progress";
    default:
      return "Not started";
  }
}
</script>

<style scoped>
.onboard-card {
  border: 1px solid var(--c-border);
  border-radius: 12px;
  padding: 16px;
  background: var(--c-bg);
}
.onboard-title { margin: 0 0 6px 0; }
.onboard-subtitle { margin: 0 0 14px 0; color: var(--c-text-quote); }

.onboard-error {
  padding: 10px 12px;
  border: 1px solid var(--c-border);
  border-radius: 10px;
  background: var(--c-bg-soft);
}

.onboard-summary {
  display: grid;
  gap: 8px;
  margin-bottom: 14px;
}

.onboard-bar {
  height: 10px;
  border-radius: 999px;
  background: var(--c-bg-light);
  overflow: hidden;
  border: 1px solid var(--c-border);
}
.onboard-bar-fill { height: 100%; background: var(--c-brand); }
.onboard-percent { color: var(--c-text-quote); }

.onboard-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}
@media (max-width: 900px) {
  .onboard-grid { grid-template-columns: 1fr; }
}

.onboard-region {
  border: 1px solid var(--c-border);
  border-radius: 10px;
  padding: 12px;
  background: var(--c-bg-soft);
}

.onboard-region-header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 8px;
}
.onboard-region-name { font-weight: 700; }
.onboard-region-count { color: var(--c-text-quote); }

.onboard-groups { list-style: none; padding: 0; margin: 0; display: grid; gap: 6px; }
.onboard-group { display: grid; grid-template-columns: auto 1fr auto; gap: 8px; align-items: center; }

.badge {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 999px;
  border: 1px solid var(--c-border);
  background: var(--c-bg);
}
.badge-complete { border-color: rgba(0,128,0,.35); }
.badge-scheduled { border-color: rgba(255,165,0,.45); }
.badge-in_progress { border-color: rgba(0,120,255,.45); }
.badge-not_started { opacity: 0.8; }

.group-date { color: var(--c-text-quote); font-variant-numeric: tabular-nums; }
.onboard-upcoming { margin-top: 14px; }
.onboard-upcoming-title { margin: 0 0 6px 0; }

.region-flash {
  outline: 3px solid var(--c-brand);
  outline-offset: 4px;
  border-radius: 12px;
  transition: outline-color 0.9s ease;
}
</style>
